version: '3.9'

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "${API_PORT}:8000"
    command: /bin/sh -c "alembic upgrade head && uvicorn --factory main:create_app --reload --host 0.0.0.0 --port 8000"
    restart: always
    env_file:
      - ../.env
    depends_on:
      - postgres
    volumes:
      - ../app/:/app/
    networks:
      - backend

networks:
  backend:
    driver: bridge